apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: kafka-cloud-events-poc
manifests:
  rawYaml:
  - ./infra/**/*.yaml
  - ./infra/*.yaml
  - ./consumer/k8s/*.yaml
  - ./producer/k8s/*.yaml
deploy:
  statusCheckDeadlineSeconds: 600
build:
  local:
    push: false
  artifacts:
  - image: bhushan629/consumer
    context: consumer
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "**/**/*.js"
        dest: .
  - image: bhushan629/producer
    context: producer
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "**/**/*.js"
        dest: .
  