apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-schema-registry-ui-deploy
  name: kafka-schema-registry-ui
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: kafka-schema-registry-ui-deploy
