apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper-deploy
  name: zookeeper-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-deploy
  template:
    metadata:
      labels:
        network/kafka-network: "true"
        app: zookeeper-deploy
    spec:
      volumes:
        - name: zookeeper-data
          hostPath:
            path: /cluster-data/zookeeper-data
            type: DirectoryOrCreate
      containers:
      - image: confluentinc/cp-zookeeper:7.0.1
        name: zookeeper
        ports:
        - containerPort: 2181
        env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"
          - name: ZOOKEEPER_SERVER_ID
            value: "1"
        volumeMounts:
          - mountPath: /var/lib/zookeeper
            name: zookeeper-data
