apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-deploy
  name: kafka
spec:
  ports:
  - name: internal
    port: 29092
    targetPort: 29092
  - name: external
    port: 9092
    targetPort: 9092
  selector:
    app: kafka-deploy
