apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-schema-registry
  name: kafka-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-schema-registry
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-schema-registry
    spec:
      initContainers:
      - name: check-kafka-server
        image: busybox:latest
        command: ['sh', '-c', 'until nc -vz $SERVICENAME $PORT; do echo "Waiting for zookeeper service"; sleep 2; done;']
        env:
          - name: SERVICENAME
            value: kafka
          - name: PORT
            value: "9092"
      enableServiceLinks: false
      containers:
      - image: confluentinc/cp-schema-registry:7.0.1
        name: cp-schema-registry
        ports:
        - containerPort: 30081
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: "schema-registry"
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        - name: SCHEMA_REGISTRY_LISTENERS
          value: "http://0.0.0.0:30081"
status: {}
