apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-schema-registry
  name: kafka-schema-registry
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 30081
  selector:
    app: kafka-schema-registry
